### ISSUE TITLE
Badly Compressed Packet (Fluid Pump)

### ISSUE THREAD

**Issue by jessiewestlake** [NerdHubMC/Refined-Machinery#14]
Running on a multiplayer server: When placing a fluid pump in water the client disconnects from the server with the error `Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 6879333 is larger than the protocol maximum of 2097152`.

The client doesn't crash, it just disconnects. I can go back into the server and see a flash of the world, and I can tell the fluid pump sucked up some water blocks. But the client disconnects within a few milliseconds of logging in and I get the same error. The server never crashes or anything.

**Comment by alothmanmoe** [comment]
interesting, will test it out in just a little here

**Comment by alothmanmoe** [comment]
Got it fixed now in https://github.com/NerdHubMC/Refined-Machinery/commit/c2e4e4fed34888b739d83942a146a8178c3be5bb

**Comment by jessiewestlake** [comment]
I built from source (I believe I did it right) and when using the mod, the client crashes with this general error:
````
[15:56:18] [main/WARN]: Error loading class: net/minecraft/client/render/entity/LivingEntityRenderer (java.lang.ClassNotFoundException: net/minecraft/client/render/entity/LivingEntityRenderer)
[15:56:18] [main/WARN]: @Mixin target net.minecraft.client.render.entity.LivingEntityRenderer was not found refinedmachinery.mixins.json:MixinLivingEntityRenderer
[15:56:18] [main/WARN]: Error loading class: net/minecraft/client/render/GameRenderer (java.lang.ClassNotFoundException: net/minecraft/client/render/GameRenderer)
[15:56:18] [main/WARN]: @Mixin target net.minecraft.client.render.GameRenderer was not found refinedmachinery.mixins.json:MixinGameRenderer
````
[crash-2019-05-12_15.56.21-client.txt](https://github.com/NerdHubMC/Refined-Machinery/files/3170503/crash-2019-05-12_15.56.21-client.txt)

**Comment by UpcraftLP** [comment]
>I built from source (I believe I did it right)

looks like you did NOT build it right, you need to run the `build` gradle task

**Comment by alothmanmoe** [comment]
As upcraft said you probably haven’t built it correctly as I have it working in dev and compiled, also you will run into a few issues as it needs the latest build of cardinal energy which I haven’t pushed yet and the latest AbusedLib as there’s been a lot of changes

**Comment by jessiewestlake** [comment]
I finally got the mod compiled properly, but I still get the same exact error when trying to log on to my server. I updated the server and the client mod. I know that Cardinal Energy and AbusedLib still need to be updated, but I was thinking at least this one thing would be working which would allow me to get into the server and remove the Fluid Pump, without losing all my Energized Ingots XD.

**Comment by alothmanmoe** [comment]
Ahh i see, the problem might persist even if you update the mod though as the reason it disconnected was the fluid was storing too much data in its nbt, once the data is saved the only way to get rid of it is to break the block/remove it, so any new fluid pumps will be fine but existing ones would have to be replaced, you could try getting the block position of it and removing it in console, and then just spawning a new one in once you join

**Comment by jessiewestlake** [comment]
That is a good suggestion. Thanks abused!

**Comment by alothmanmoe** [comment]
Last version for 1.14 just got released, waiting for curse to approve and working on 1.14.1
